import Link from "next/link";

export default function Home(){return <main className="mx-auto max-w-6xl px-5 py-10 md:py-20">
  <section className="grid min-h-[66vh] items-center gap-10 md:grid-cols-[1.35fr_.8fr] md:gap-16">
    <div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-teal">A calmer first step</p><h1 className="display my-4 text-5xl font-semibold leading-[1.02] md:text-7xl">Say what’s wrong.<br/>We’ll help organise it.</h1><p className="mb-8 max-w-xl text-lg text-slate-600">Ask first. No account needed. Nightingale AI is not a doctor.</p><div className="flex flex-wrap items-center gap-4"><Link className="focus-ring rounded-xl bg-teal px-5 py-3 font-bold text-white" href="/start?source_channel=instagram_ad_click&source_platform=instagram&campaign_id=ivf_over40&creative=story_a">Ask a question</Link><Link className="focus-ring font-semibold text-ink underline-offset-4 hover:underline" href="/staff">Clinic team</Link></div></div>
    <div className="rounded-3xl border border-line bg-white p-7 shadow-soft"><Principle n="01" title="Ask first">No signup.</Principle><Principle n="02" title="You choose">The clinic sees only what you consent to share.</Principle><Principle n="03" title="Safety first">Urgent concerns interrupt everything else.</Principle></div>
  </section>
  <section className="rounded-2xl border border-line bg-white p-6"><p className="text-xs font-bold uppercase tracking-wider text-teal">Synthetic demo</p><h2 className="mt-2 text-xl font-bold">Clinic workspace</h2><p className="mt-2 text-slate-600">Staff authentication is owned by the backend team. Mock mode opens synthetic staff data only.</p><Link className="mt-4 inline-block rounded-xl border border-teal px-4 py-2 font-bold text-teal" href="/staff">Open workspace</Link></section>
</main>}
function Principle({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <div className="grid grid-cols-[2rem_1fr] gap-2 border-b border-line py-4 last:border-0"><span className="text-sm font-bold text-teal">{n}</span><div><strong>{title}</strong><p className="mt-1 text-sm text-slate-500">{children}</p></div></div>}
