// src/contracts/index.ts

/**
 * 1. User & Identity Types
 */
export type UserRole = 'patient' | 'clinician' | 'nurse' | 'staff';

export interface User {
  id: string; // Immutable internal ID
  email?: string;
  phone?: string;
  social_handles?: {
    instagram?: string;
    tiktok?: string;
    facebook?: string;
  };
  role: UserRole;
  created_at: string;
  updated_at: string;
}

/**
 * 2. Channel & Attribution Session Types
 */
export type ChannelSource =
  | 'staff_referral'
  | 'social_comment'
  | 'instagram_ad_click'
  | 'google_ad_click'
  | 'lead_form'
  | 'google_reviews'
  | 'website_widget';

export type IdentityLevel = 'anonymous' | 'identified';

export interface BaseSession {
  id: string;
  clinic_id: string;
  source_channel: ChannelSource;
  campaign_id?: string;
  creative?: string;
  identity_level: IdentityLevel;
  landing_timestamp: string;
}

// Unauthenticated guest session
export interface LeadSession extends BaseSession {
  is_authenticated: false;
  guest_metadata?: Record<string, unknown>;
}

// Authenticated patient session preserving initial attribution & provenance
export interface PatientSession extends BaseSession {
  is_authenticated: true;
  patient_id: string; // Links to User.id
  verified_email: string;
  verified_phone: string;
  consented_at: string;
  marketing_consent: boolean;
}

/**
 * 3. Living Memory Types
 */
export type MemoryCategory = 'chief_complaint' | 'medications' | 'allergies' | 'key_symptoms';
export type MemoryStatus = 'active' | 'stopped' | 'updated' | 'removed';

export interface MemoryItem {
  id: string;
  session_id?: string;
  patient_id: string;
  category: MemoryCategory;
  value: string;
  status: MemoryStatus;
  provenance_pointer?: string; // Message ID where fact was extracted or updated
  updated_at: string;
}

/**
 * 4. Escalation & Triage Payload Types
 */
export type RiskLevel = 'Low' | 'Med' | 'High';
export type EscalationStatus = 'pending_review' | 'in_progress' | 'resolved';

export interface EscalationPayload {
  id: string;
  session_id: string;
  patient_id: string;
  triggering_message_id: string;
  triggering_message_content: string;
  triage_summary: string[]; // 1-5 bullet points generated by AI
  profile_snapshot: MemoryItem[];
  risk_level: RiskLevel;
  risk_reason?: string;
  acquisition_context: {
    source_channel: ChannelSource;
    campaign_id?: string;
    landing_timestamp: string;
  };
  status: EscalationStatus;
  clinician_response?: string;
  created_at: string;
  updated_at: string;
}

/**
 * 5. PHI-Free Audit Event Types
 */
export type AuditEventType =
  | 'visitor_landed'
  | 'value_event'
  | 'auth_started'
  | 'visitor_consented'
  | 'patient_created'
  | 'escalation_sent'
  | 'access_denied';

export interface AuditEvent {
  id: string;
  timestamp: string;
  event_type: AuditEventType;
  clinic_id: string;
  session_id?: string;
  user_id_hash?: string; // Anonymized/hashed identifier (NO raw PHI)
  metadata: Record<string, unknown>; // Metadata only—never raw chat content
}